### ISSUE TITLE
Investigate using P8CII for textbox

### ISSUE THREAD

**Issue by akinlin** [akinlin/Pico#24]
What are the benefits?
 - Access to control codes - https://pico-8.fandom.com/wiki/P8SCII_Control_Codes
 - Access to expanded character set including symbols, and Japanese characters 
Is there better control for handling line breaks and fitting text within a defined space?
 - Control codes do appear to give a better way to handle text management
Can it help with font changes?
 - Yes, it includes the \14 & \15 control codes to switch fonts
Can it help with font styles (bold, italics)
 - There are basic attributes that can be applies (tall, dotted) but not specifically bold or italics, will need further investigation.
Can it help with animation?
 - Control code could help with is by offsetting the cursor 

- [ ] Try out changing a font
- [ ] Test text animation
- [ ] Test Bold and Italics
- [ ] #28

**Comment by akinlin** [comment]
Reference details: https://pico-8.fandom.com/wiki/P8SCII
